packages/rich-text-from-markdown/src/index.ts, packages/rich-text-from-markdown/src/types/index.ts, packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts, packages/rich-text-types/src/nodeTypes.ts
- Updates `rich-text-links`'s `getRichTextEntityLinks()` to return _all_ entity links when no `linkType` is provided.
- Previously we required the second `linkType` parameter. But in some cases (e.g. when enforcing publication constraints on link count), we really only care how many entity links _total_ appear in a rich text field, regardless of whether they qualify as "Entry" or "Asset" links.
- Ships a small stylistic change to prefer condensed single-type array type declaration syntax where possible.
- e.g. `Array<Node>` -> `Node[]`
Will be pulled in as part of [AUTH-716](https://contentful.atlassian.net/browse/AUTH-716).
=> Return all entity links when no linkType is provided

packages/rich-text-types/src/nodeTypes.ts, packages/rich-text-types/src/schemas/__test__/__snapshots__/schemas.test.ts.snap, packages/rich-text-types/src/schemas/generated/asset-hyperlink.json, packages/rich-text-types/src/schemas/generated/entry-hyperlink.json, packages/rich-text-types/src/schemas/generated/hyperlink.json
PR removes currently unused field `title` from Hyperlinks definition
=> fix: 🐛 Removes obsolete field `title` from Hyperlinks

CONTRIBUTING.md, package.json, packages/rich-text-links/README.md, packages/rich-text-links/bin/benchmark/get-rich-text-links.ts, packages/rich-text-links/bin/benchmark/index.ts, packages/rich-text-links/bin/tsconfig.json, packages/rich-text-links/bin/tslint.json, packages/rich-text-links/package-lock.json, packages/rich-text-links/package.json, packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts
- Simplifies the return value of `getRichTextEntityLinks`, while adding a ~2x performance improvement.
- when testing this as a `rollup`ed package in `@contentful/models` and running against the benchmark script in that repository, I consistently got ~500k ops/sec results vs the current perf of ~950k ops/sec.
- we should expect an even greater perf increase in other back-end repos, which are not using the optimized `@contentful/models` algo.
- **BREAKING CHANGE:** Produces an entirely new return value and obviates the `linkType` parameter (all entities are grouped and returned by default).
- Pulls in `getRichTextEntityLinks` benchmark from `@contentful/models`, adapts to TypeScript, and creates the basis for systematic benchmarking, including documentation in CONTRIBUTING.md.
I noticed …
=> Improve rich-text-links and add benchmarking

packages/rich-text-links/bin/benchmark/get-rich-text-entity-links.ts
Corrects the nomenclature in the filename and benchmark title.
(no need for an immediate version bump or anything, just something that needed to be changed before we forget about it)
=> refactor: 💡 (nit) rename from richTextLinks to richTextEntityLinks

packages/rich-text-types/package-lock.json, packages/rich-text-types/package.json, packages/rich-text-types/src/index.ts
Polyfills Object.values, without which this module is incompatible with `@contentful/validation` in CI (maybe in other respects).
Also makes this a friendlier export for our friends using es5 without a polyfill in their Babel step.
I simply scoped the polyfill to `@contentful/rich-text-types` (not the repo as a whole, or as a component of the rollup compilation step) since we should attempt to minimize the amount of compatibility cruft we're throwing into each module.
Affects https://github.com/contentful/contentful-validation/pull/126, which pulls in a new major version of this dependency and consequently fails the CI step.
=> fix: 🐛 add es7-object-polyfill

README.md, packages/gatsby-transformer-contentful-richtext/.gitignore
This PR adds a `.gitignore` file specifically for the Gatsby transformer plugin
=> Add gitignore and add missing package link to README

packages/rich-text-from-markdown/src/__test__/index.test.ts, packages/rich-text-from-markdown/src/index.ts
Currently, `rich-text-from-markdown` doesn't handle hyperlinks, because it ignores all `inline` types. This fixes that.
I'm not sure if everything I wrote is necessary — e.g., adding the `data: nodeData` key — but I was just trying to keep it consistent with the code above it. (I'm not super familiar with rich text and its AST.)
=> fix: handle hyperlinks

packages/rich-text-html-renderer/package-lock.json, packages/rich-text-html-renderer/package.json, packages/rich-text-html-renderer/src/__test__/index.test.ts, packages/rich-text-html-renderer/src/index.ts
PR adds html escaping to the html renderer. The text value will be escaped before passing to the mark renderers.
Example
```js
documentToHtmlString({
nodeType: BLOCKS.DOCUMENT,
data: {},
content: [
{
nodeType: BLOCKS.PARAGRAPH,
data: {},
content: [
{
nodeType: 'text',
value: 'foo & bar',
marks: [{ type: MARKS.UNDERLINE }, { type: MARKS.BOLD }],
data: {}
}
]
}
]
});
```
Previous result:
```html
<p><b><u>foo & bar</u></b></p>
```
Current result:
```html
<p><b><u>foo &amp; bar</u></b></p>
```
=> Add html escaping to html renderer

README.md
Adds a link to [`rich-text-to-jsx`](https://github.com/connor-baer/rich-text-to-jsx), a package that renders a Contentful Rich Text document to JSX for use in React.
_(Disclaimer: I maintain this package)_
=> Add link to rich-text-to-jsx

package.json, packages/rich-text-from-markdown/src/__test__/index.test.ts
Update Jest types to 23.3.12 in main package and fix markdown tests on
nodes missing the `data` field mandated by their type Node
=> chore: 🤖 Update Jest types to 23.3.12

README.md, jest.config.js, lerna.json, packages/gatsby-transformer-contentful-richtext/README.md
PR adds deprecation notes for `gatsby-transformer-contentful-richtext` packages.
=> Deprecate gatsby-transformer-contentful-richtext

packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts
So that TypeScript in graph-api stops reporting an import error.
=> refactor: 💡 Use named export for getRichTextEntityLinks

README.md
Started a rich-text renderer for Flutter (written in Dart) and wanted to share it with the community. We are interested in help fleshing out the various widgets, and it is still in a relatively early "work-in-progress" phase. But it does work, it allows Flutter widgets to be passed in to override the defaults and has the basic widgets defined so far. It was loosely based on the Contentful Typescript renderer.
Also happy to get issue reports and code reviews (probably could use some cleanup), but time to work on them may be limited for the next month or two.
Fixes #82
=> Add Flutter renderer to community-made section in readme

packages/rich-text-react-renderer/README.md
Hey, while integrating this feature I noticed the shape of data is incorrect in the README
=> fix shape of embedded node in README

packages/rich-text-react-renderer/src/__test__/__snapshots__/index.test.tsx.snap, packages/rich-text-react-renderer/src/__test__/components/Document.tsx, packages/rich-text-react-renderer/src/__test__/index.test.tsx, packages/rich-text-react-renderer/src/index.tsx
Enables the option renderNode[BLOCKS.DOCUMENT] with
rich-text-react-renderer, defaulting to current Array output.
✅ Closes: #104
I kept the existing behaviour of rendering an array of ReactNodes to avoid breaking existing uses. Specifying `renderNode[BLOCKS.DOCUMENT]` can enable a root element if wanted.
=> feat: 🎸 Adds BLOCKS.DOCUMENT renderer support to react-renderer

packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts
We have previously been treating nodes having `content` and nodes having `data` as being mutually exclusive. The result is that `rich-text-links` ignores the `content` of nodes that are parents to nodes containing embedded block or inline entity links*.
* NB: this tool doesn't technically check the `nodeType`, that's just the most common use-case so I refer to it here for clarity's sake.
Technically, I think this runs against spec but our UI behaves otherwise and in any case I don't really see the harm (philosophically) in making this a dumb scraper for `data` nodes with entity links.
Performance-wise, this moves the tool from seeking for only a subset of all nodes (those without `data` attributes) to _all_ nodes within a document. I think this is low-risk (since documents generated by …
=> [PEN-782] fix: 🐛 detect links as children of nodes also having links

packages/rich-text-html-renderer/package-lock.json, packages/rich-text-html-renderer/package.json, packages/rich-text-html-renderer/src/__test__/index.test.ts, packages/rich-text-html-renderer/src/index.ts
Using a `hyperlink` node with e.g. `data.uri = '"><h1>html</h1><a href="'`, it was possible to inject arbitrary HTML next to the actual hyperlink. We encode `"` within the `href` attribute. The same technique should be applied for all attributes if added in the future.
=> fix: 🐛 prevent html injection via `data.uri` link rendering

packages/rich-text-html-renderer/src/__test__/index.test.ts
Fixes the import that caused incorrect types folder structure in `rich-text-html-renderer`
Fixes #252 and #259
=> fix: replace import to fix typings for html-renderer

packages/rich-text-types/src/__test__/schemaConstraints.test.ts, packages/rich-text-types/src/schemaConstraints.ts
`TEXT_CONTAINERS` are all block node types that aren't `CONTAINERS` (block nodes that can contain other block nodes) or void nodes (nodes that do not have any content whatsoever).
=> feat(rich-text-types): Add TEXT_CONTAINERS

package-lock.json, packages/contentful-slatejs-adapter/package-lock.json, packages/contentful-slatejs-adapter/package.json, packages/contentful-slatejs-adapter/src/__test__/contentful-helpers.ts, packages/contentful-slatejs-adapter/src/__test__/contentful-to-slatejs-adapter.test.ts, packages/contentful-slatejs-adapter/src/contentful-to-slatejs-adapter.ts, packages/contentful-slatejs-adapter/src/schema.ts, packages/contentful-slatejs-adapter/src/slatejs-to-contentful-adapter.ts, packages/rich-text-html-renderer/package-lock.json
Depends on change in #286
`content` for any `TEXT_CONTAINER` contentful node could be empty according to our CMA validation rules, but we want consistent handling, even if we upgrade to a future SlateJS versions that might introduce different handling like not always inserting empty text leaves.
With this change we ensure that:
1. The output contentful document's block nodes' `content` always includes at least an empty text node, unless it's a node type supposed to be void or supposed to contain other block nodes.
2. The output SlateJS document's block nodes' `children` always includes at least an empty text node, unless it's a node type supposed to be void or supposed to contain other block nodes.
=> feat: add toContentfulDocument() and toSlatejsDocument() empty block node handling

package-lock.json, packages/contentful-slatejs-adapter/package-lock.json, packages/rich-text-html-renderer/package-lock.json, packages/rich-text-links/src/__test__/index.test.ts
Adds table node with inline embeds in a header/cell to the links resolving test.
=> test: add inline embeds in table to links test

package-lock.json, packages/contentful-slatejs-adapter/package-lock.json, packages/rich-text-html-renderer/package-lock.json, packages/rich-text-types/package.json, packages/rich-text-types/rollup.config.js, packages/rich-text-types/src/helpers.ts, packages/rich-text-types/src/index.ts, packages/rich-text-types/src/schemas/__test__/helpers.test.ts, packages/rich-text-types/tsconfig.json
Using the new `validateRichTextDocument` fails due to `require('./generated/{nodeType}.json')` unable to resolve the file.
**Before**:
```
dist/
lib/
schemas/
generated/
index.js // importing the helper directly works
rich-text-types.es5.js // a single bundle of the whole source code. It fails to locate ./generated
```
**After**:
```
dist/
schemas/
generated/
index.js // importing the helper directly still works
index.js // now calls schemas/generated/index.js since the code no longer bundled together.
```
=> fix(rich-text-types): resolve generated JSON schemas

packages/rich-text-react-renderer/src/__test__/__snapshots__/index.test.tsx.snap, packages/rich-text-react-renderer/src/index.tsx
Fixes the following warning:
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
```
=> fix(react-renderer): wrap table rows in tbody

tsconfig.json
This is to fix the bug where source files are not included in the packages exported from this repo (namely `rich-text-types` was causing an issue in apps using rich-text). In order to match the `field-editors` package, it was decided that the source files should be built inline.
=> fix: add inline sources to packages

.circleci/config.yml, CONTRIBUTING.md, deprecated/gatsby-transformer-contentful-richtext/package.json, package.json, packages/contentful-slatejs-adapter/package.json, packages/rich-text-types/package.json
`lerna publish --from-git` fails with 404 error. This doesn't happen locally so it's hard to debug. While searching I noticed that we don't need lerna to publish since all the version bumping + changelog + GH release happens in the `lerna version` step.
So for our use case, `lerna publish` should be the same as running `npm publish` in all packages and that's what this PR is about to unblock publishing. 
Additionally I updated some READMEs to mention `yarn` instead of `npm run`.
This works locally but will have to wait for the CI 🤞🏻
=> build(release): run npm publish directly

.circleci/config.yml
The release job had no access to the npm token.
=> build(ci): set npm token for the release job

packages/contentful-slatejs-adapter/package.json
When using this module somewhere else, we get TS errors due to missing exported types. It turned out that the `package.json` is pointing to a non-existing file.
=> fix: entrypoint for types of package [HOMER-1842]

packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts
This is needed to support use-cases where you are interested in the duplicate values of which we currently have two:
1. Counting the total amount of ResourceLink references or when generating a diff between the old and new entry state
2. Validating if a duplicate ResourceLink is added/removed (used for fencing)
=> feat: add deduplicate option to getRichTextResourceLinks  [DANTE-1028]

packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts, packages/rich-text-links/src/types/utils.ts
As an immediate action of [this postmortem](https://contentful.atlassian.net/wiki/spaces/ENG/pages/4240343365/2023-05-30+500+errors+on+entry+save+if+RichText+field+had+null+values) we decided to let the public type reflect the expected type that is passed to the function. 
This means that the type is now less strict which will make it clearer why we deliberately check for `null` values in our library code. This should cause this exact issue to not happen again (by accident) in the future.
=> feat: allow document parameter of getRichTextEntityLinks to be nullable []

packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts, packages/rich-text-types/src/inlines.ts, packages/rich-text-types/src/nodeTypes.ts, packages/rich-text-types/src/schemas/__test__/__snapshots__/schemas.test.ts.snap, packages/rich-text-types/src/schemas/generated/blockquote.json, packages/rich-text-types/src/schemas/generated/document.json, packages/rich-text-types/src/schemas/generated/embedded-asset-block.json, packages/rich-text-types/src/schemas/generated/embedded-entry-block.json, packages/rich-text-types/src/schemas/generated/embedded-resource-block.json, packages/rich-text-types/src/schemas/generated/embedded-resource-inline.json, packages/rich-text-types/src/schemas/generated/heading-1.json, packages/rich-text-types/src/schemas/generated/heading-2.json, packages/rich-text-types/src/schemas/generated/heading-4.json, packages/rich-text-types/src/schemas/generated/heading-5.json, packages/rich-text-types/src/schemas/generated/heading-6.json, packages/rich-text-types/src/schemas/generated/hr.json, packages/rich-text-types/src/schemas/generated/list-item.json, packages/rich-text-types/src/schemas/generated/ordered-list.json, packages/rich-text-types/src/schemas/generated/paragraph.json, packages/rich-text-types/src/schemas/generated/resource-hyperlink.json, packages/rich-text-types/src/schemas/generated/table-cell.json, packages/rich-text-types/src/schemas/generated/table-header-cell.json, packages/rich-text-types/src/schemas/generated/table-row.json, packages/rich-text-types/src/schemas/generated/table.json, packages/rich-text-types/src/schemas/generated/unordered-list.json, packages/rich-text-types/tools/jsonSchemaGen.ts
- Add `embedded-resource-inline` and `resource-hyperlink` nodes
- `getAllRichTextResourceLinks` to find all resource links regardless of node type
[DANTE-1157](https://contentful.atlassian.net/browse/DANTE-1157)
[DANTE-1157]: https://contentful.atlassian.net/browse/DANTE-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add new nodes [DANTE-1157]

packages/rich-text-html-renderer/src/__test__/index.test.ts, packages/rich-text-html-renderer/src/index.ts, packages/rich-text-react-renderer/src/__test__/__snapshots__/index.test.tsx.snap, packages/rich-text-react-renderer/src/__test__/index.test.tsx, packages/rich-text-react-renderer/src/index.tsx, packages/rich-text-react-renderer/src/util/nodeListToReactComponents.tsx
Fixes [#96](https://github.com/contentful/rich-text/issues/96)
Ticket: https://contentful.atlassian.net/browse/TOL-1056
The current behavior of the rich-text-html-renderer ignores line breaks, similar to standard browser behavior. This has caused discrepancies between content editor expectations and actual output. Furthermore, extra spaces between words are also not rendered.
To address this without introducing breaking changes, this PR introduces an optional configuration that instructs the renderer to generate HTML that aligns closer to what content editors would expect.
- Implemented the ability to pass an optional configuration to the render function.
- When the configuration is passed, the renderer automatically adds an extra `<br/>` tag for each new line in the Rich Text Editor.
- …
=> feat: preserve whitespace (linebreak and multiple spaces)  [TOL-1056]

packages/rich-text-html-renderer/README.md, packages/rich-text-react-renderer/README.md, packages/rich-text-react-renderer/src/__test__/__snapshots__/index.test.tsx.snap, packages/rich-text-react-renderer/src/__test__/index.test.tsx
- remove `.only` in test case
- unrelated snapshots were updated (after auto formatting) in the last PR, which made the tests fail. I reversed those changes.
- add documentation around newly added preserve whitespace option
=> docs: describe preserve whitespace [TOL-1056]

packages/rich-text-plain-text-renderer/src/index.ts
There's an edge case in this [ticket](https://contentful.atlassian.net/jira/software/c/projects/ZEND/boards/254?quickFilter=711&selectedIssue=ZEND-4744) where the HTML UI extension doesn't validate the rich text data correctly & sends us this content as a string not an array of valid node
We have added a check to see if content is an array
=> fix: correctly handle edge case [ZEND-4744]

packages/rich-text-types/src/nodeTypes.ts, packages/rich-text-types/src/schemas/__test__/__snapshots__/schemas.test.ts.snap, packages/rich-text-types/src/schemas/generated/table-cell.json, packages/rich-text-types/src/schemas/generated/table-header-cell.json, packages/rich-text-types/src/schemas/generated/table-row.json, packages/rich-text-types/src/schemas/generated/table.json
updating schema for rich text type change in #616. this breaks tests as shown [here](https://app.circleci.com/pipelines/github/contentful/rich-text/1340/workflows/2585ea7a-f536-497e-9688-2c2ad92e701b/jobs/2797?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) which we fixed by updating the snapshots
=> feat: update schema for rich text types [TOL-2249]

packages/rich-text-types/src/index.ts
Exporting from index so it's not imported from `@contentful/rich-text-types/dist/schema`
=> fix: exporting schema function []

.github/workflows/auto-approve.yml
Adding this so we don't have to manually merge dependapot PRs which will allow us to focus on the ones that fail
=> chore: allow auto merge [TOL-2260]

.husky/pre-commit
when we run yarn on the CI husky makes a change to the pre commit script to remove deprecated steps which causes the CI to fail. This PR applies the change so that we don't generate a change in the CI
=> chore: fix pipeline by running husky locally

packages/rich-text-html-renderer/src/__test__/index.test.ts, packages/rich-text-html-renderer/src/index.ts, packages/rich-text-plain-text-renderer/src/__test__/index.test.ts, packages/rich-text-plain-text-renderer/src/index.ts, packages/rich-text-react-renderer/src/__test__/__snapshots__/index.test.tsx.snap, packages/rich-text-react-renderer/src/__test__/index.test.tsx, packages/rich-text-react-renderer/src/index.tsx, packages/rich-text-types/src/__test__/helpers.test.ts, packages/rich-text-types/src/helpers.ts
allow renderers to pass configurable stripEmptyTrailingParagraph option in order to skip trailing paragraph
=> feat: add an option to strip empty trailing paragraphs [TOL-3193]
