contentful/rich-text

packages/rich-text-html-renderer/package.json, packages/rich-text-plain-text-renderer/package.json
PR updates paths to the TS definitions.
=> [AUTH-765] update path to typings file

packages/gatsby-transformer-contentful-richtext/.babelrc.js, packages/gatsby-transformer-contentful-richtext/README.md, packages/gatsby-transformer-contentful-richtext/package-lock.json, packages/gatsby-transformer-contentful-richtext/package.json, packages/gatsby-transformer-contentful-richtext/src/__tests__/__snapshots__/gatsby-node.js.snap, packages/gatsby-transformer-contentful-richtext/src/__tests__/extend-node.js, packages/gatsby-transformer-contentful-richtext/src/__tests__/gatsby-node.js, packages/gatsby-transformer-contentful-richtext/src/extend-node-type.js, packages/gatsby-transformer-contentful-richtext/src/gatsby-node.js, packages/gatsby-transformer-contentful-richtext/src/on-node-create.js
Add `gatsby-transformer-contentful-richtext`
Preview: 👉 https://5c04e8120097d47b3409bbbe--loudmouth.netlify.com/blog/suckaz-post
=> Add `gatsby-transformer-contentful-richtext`

packages/rich-text-html-renderer/README.md, packages/rich-text-plain-text-renderer/README.md
Fixed issue https://github.com/contentful/rich-text/issues/32
=> Fix mark types in Readme examples

packages/rich-text-from-markdown/src/__test__/real-world.test.ts
PR fixes import path in one of the test modules.
=> fix: fix import path

package-lock.json, package.json, packages/rich-text-from-markdown/src/__test__/index.test.ts, packages/rich-text-from-markdown/src/index.ts
PR adds the ability to parse links within marks and adds tests for nested marks.
=> Parse links within marks

packages/gatsby-transformer-contentful-richtext/package-lock.json, packages/gatsby-transformer-contentful-richtext/package.json, packages/gatsby-transformer-contentful-richtext/src/__tests__/extend-node.js, packages/gatsby-transformer-contentful-richtext/src/extend-node-type.js
Reference implementation - https://github.com/gatsbyjs/gatsby/blob/29a8c5cce409bd69da1ec8076ff6b9b79729247e/packages/gatsby-transformer-remark/src/extend-node-type.js#L485
=> feat: 🎸 add time to read for reach text

jest.config.js
PR improves test coverage report by excluding test and aux files.
```
--------------------------------------------|----------|----------|----------|----------|-------------------|
File                                        |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                   |    95.18 |     88.5 |    88.89 |    95.07 |                   |
gatsby-transformer-contentful-richtext/src |    92.86 |       75 |      100 |    92.86 |                   |
extend-node-type.js                       |    93.33 |       80 |      100 |    93.33 |             15,30 |
gatsby-node.js                            |      100 |      100 | …
```
=> Improve test coverage report

packages/rich-text-links/package.json, packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts
=> feat: 🎸 Support filtering by node name in rich-text-links

packages/contentful-slatejs-adapter/tsconfig.json, packages/rich-text-types/rollup.config.js
Files were not properly copied to dist folder.
=> fix: 🐛 configure rollup copy correctly

packages/rich-text-react-renderer/package.json
https://github.com/contentful/rich-text/issues/199
=> feature: bump peer dependency version to allow for React  v17

packages/contentful-slatejs-adapter/package.json
=> fix(slatejs-adapter): release as public package

packages/rich-text-types/src/nodeTypes.ts, packages/rich-text-types/src/schemas/__test__/__snapshots__/schemas.test.ts.snap, packages/rich-text-types/src/schemas/generated/table-cell.json, packages/rich-text-types/src/schemas/generated/table-row.json, packages/rich-text-types/src/schemas/generated/table.json
follows https://github.com/contentful/rich-text/pull/239
=> feat: add rowspan

package-lock.json, packages/gatsby-transformer-contentful-richtext/package-lock.json, packages/rich-text-react-renderer/package-lock.json
It aims to fix and other high severity vulnerabilities:
=> Fix critical vulnerability alerts

packages/rich-text-from-markdown/README.md, packages/rich-text-from-markdown/src/__test__/real-world.md, packages/rich-text-from-markdown/src/__test__/real-world.test.ts, packages/rich-text-from-markdown/src/index.ts
Reverts contentful/rich-text#298
=> feat: support converting tables from markdown to rich-text

.circleci/config.yml, .contentful/compressed-size.yml, package.json
Adding circle ci workflow jobs
> Looks like we have some files that are not linted or formatted and we have some failing tests
=> ci: add circle ci config workflow

.circleci/config.yml
Circleci is failing on master, despite passing on PRs, likely due to the increased load of generating inline sourcemaps.
=> fix: circleci update resource class

packages/contentful-slatejs-adapter/package.json, packages/rich-text-from-markdown/package.json, packages/rich-text-html-renderer/package.json, packages/rich-text-links/package.json, packages/rich-text-plain-text-renderer/package.json, packages/rich-text-react-renderer/package.json, packages/rich-text-types/package.json
Just looking for some changes that touch the packages/ to trigger a release :)
=> chore: remove unnecessary gitHeads

packages/rich-text-links/src/__test__/index.test.ts, packages/rich-text-links/src/index.ts, packages/rich-text-types/src/inlines.ts
Add ability to retrieve node types pointing to `ResourceLink` links.
=> feat: 🎸 add `getRichTextResourceLinks`

.contentful/vault-secrets.yaml
Adding `packages-read` policy to vault secrets
=> chore: adding packages read to vault secrets policies [TOL-1700]

.circleci/config.yml, README.md, package.json
Triggering gh packages release
=> feat: triggering gh packages release []

package.json, packages/contentful-slatejs-adapter/package.json, packages/rich-text-from-markdown/package.json, packages/rich-text-html-renderer/package.json, packages/rich-text-links/package.json, packages/rich-text-plain-text-renderer/package.json, packages/rich-text-react-renderer/package.json, packages/rich-text-types/package.json, rollup.config.js, tsconfig.json, yarn.lock
In the TS guild, we discussed that we want to bring most of our packages to TS 5.
=> chore: update TS to version 5.3.2 and adjust config []

lerna.json, package.json, yarn.lock
upgrading lerna to the latest version & removing invalid config
=> chore: upgrade lerna [TOL-2097]

packages/rich-text-html-renderer/README.md, packages/rich-text-html-renderer/src/__test__/index.test.ts, packages/rich-text-html-renderer/src/index.ts, packages/rich-text-react-renderer/src/__test__/__snapshots__/index.test.tsx.snap, packages/rich-text-react-renderer/src/__test__/index.test.tsx, packages/rich-text-react-renderer/src/index.tsx, packages/rich-text-types/src/marks.ts
Based on the PR changes for superscript / subscript, we add support for strikethrough https://github.com/contentful/rich-text/pull/391
=> feat: add strikethrough support [TOL-1658]

packages/rich-text-types/src/nodeTypes.ts, packages/rich-text-types/src/schemas/__test__/__snapshots__/schemas.test.ts.snap, packages/rich-text-types/src/schemas/generated/table-cell.json, packages/rich-text-types/src/schemas/generated/table-row.json, packages/rich-text-types/src/schemas/generated/table.json
Reverts contentful/rich-text#619
=> fix: revert schema changes  [TOL-2249]

packages/rich-text-react-renderer/tsconfig.json, packages/rich-text-types/package.json, packages/rich-text-types/rollup.config.js, rollup.config.js
closes https://github.com/contentful/rich-text/issues/922, https://github.com/contentful/rich-text/issues/921, https://github.com/contentful/rich-text/issues/919
=> fix: bundle issues after swc migration [TOL-3396]
